chargify:
  appName: <%= ENV['CHARGIFY_APP_NAME'] %>
  host: https://<%= ENV['CHARGIFY_APP_NAME'] %>.chargify.com/
  plans:
    standard:
      name: <%= ENV['CHARGIFY_STANDARD_PLAN_NAME'] %>
      path: subscribe/<%= ENV['CHARGIFY_STANDARD_PLAN_KEY'] %>/<%= ENV['CHARGIFY_STANDARD_PLAN_NAME'] %>
    plus:
      name: <%= ENV['CHARGIFY_PLUS_PLAN_NAME'] %>
      path: subscribe/<%= ENV['CHARGIFY_PLUS_PLAN_KEY'] %>/<%= ENV['CHARGIFY_PLUS_PLAN_NAME'] %>
  donation_url: <%= ENV['CHARGIFY_DONATION_URL'] %>
